protected/controllers/CategoryController.php
<?php
class CategoryController extends Controller{

    public $layout='//layouts/simple';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl',
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'views' actions
                'actions'=>array('view','index'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('create','update'),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array(''),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }


    public function actionCreate($id = null,$lang = null)
    {
        /**
         * @var $model Category
         */
        $model = Category::model()->findByAttributes(array('id'=>$id,'language'=>$lang));
        if(!empty($model)){
            $this->redirect(array('update','id'=>$model->id,'lang'=>$model->language));
        }
        $model = new Category();
        if(!empty($id) && !empty($lang)){
            $model->id = $id;
            $model->language = $lang;
        }
        else{
            $model->language = 'ru';
        }
        $model->save();
        $this->redirect(array('update','id'=>$model->id,'lang'=>$model->language));
    }

    public function actionUpdate($id,$lang)
    {
        /**
         * @var $model Category
         */
        $this->layout = 'simple';
        $model = Category::model()->findByAttributes(array('id'=>$id,'language'=>$lang));

        if(Yii::app()->request->isPostRequest )
        {
            $model->attributes = $_POST['Category'];
            if($model->save())
                $this->redirect('/site/index');
        }

        $this->render('create',array(
            'model'=>$model
        ));
    }

    public function actionDelete($id,$lang){
        $model = Category::model()->findByAttributes(array('id'=>$id,'language'=>$lang));
        $model->delete();
        $this->redirect('/admin/categoryIndex');
    }

}

protected/controllers/ImagesController.php
<?php
class ImagesController extends  Controller{

    public function actionCreate(){
        $model = new Images();

        if(!empty($_POST['Images'])){
            /**@var $model Images*/
            $model->save();
            $img = CUploadedFile::getInstances($model, 'extension');
            if ($img)
            {
                $imagesPath = YiiBase::getPathOfAlias('webroot') . DS . 'images' . DS . 'pictures';
                foreach ($img as $avatar)
                {
                    $imageName = $avatar->name;
                    $avatar->saveAs($imagesPath . DS . 'origin_' . $imageName);
                    $imageFile= Yii::app()->image->load($imagesPath . DS . 'origin_' . $imageName);
                    $imageFile->save($imagesPath . DS . $model->id.'.' . $imageFile->ext);
                    unlink($imagesPath . DS . 'origin_' . $imageName);
                    $model->extension = $imageFile->ext;
                    $model->save();
                }
            }
            $this->redirect(array('/admin/imageIndex'));
        }

        $this->render('create',array(
            'model'=>$model
        ));
    }
}

protected/controllers/InfopageController.php
<?
class InfopageController extends Controller{

    public function filters()
    {
        return array(
            'accessControl',
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'views' actions
                'actions'=>array('contact','about','view'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('create','update','delete'),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array(''),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function actionContact(){
        $this->layout = 'simple';
        $this->render('contact',array(

        ));
    }

    public function actionAbout()
    {
        $this->layout = 'main';
        $this->render('about');
    }

    public function actionCreate($id = null,$lang = null)
    {
        /**
         * @var $model Infopage
         */
        $model = Infopage::model()->findByAttributes(array('id'=>$id,'language'=>$lang));
        if(!empty($model)){
            $this->redirect(array('update','id'=>$model->id,'lang'=>$model->language));
        }
        $model = new Infopage();
        if(!empty($id) && !empty($lang)){
            $model->id = $id;
            $model->language = $lang;
        }
        else{
            $model->language = 'ru';
        }
        $model->save();
        $this->redirect(array('update','id'=>$model->id,'lang'=>$model->language));
    }

    public function actionView($id){

        /**@var $model Infopage*/
        $arrayLanguages = array('ru','uk','en');
        $lang = $_REQUEST['languages'];

        $this->layout = "simple";
        $model = Infopage::model()->findByAttributes(array('id'=>$id,'language'=>$_REQUEST['language']));
//        if(empty($model)){
//            $language = (($_REQUEST['language'] == 'ru')?'uk':'ru');
//            $model  = Infopage::model()->findByAttributes(array('id'=>$id,'language'=>$language));
//        }
        foreach($arrayLanguages as $one){
            if($one != $lang){
            $model  = Infopage::model()->findByAttributes(array('id'=>$id,'language'=>$one));
                if(!empty($model)) break;
            }
        }

        $this->pageDescription = $model->seoDescription;
        $this->pageKeywords = $model->seoKeywords;
        $this->pageTitle = $model->seoTitle;

        $this->render('view',array(
            'model'=>$model
        ));
    }

    public function actionUpdate($id,$lang)
    {
        /**
         * @var $model Infopage
         */
        $this->layout = 'simple';
        $model = Infopage::model()->findByAttributes(array('id'=>$id,'language'=>$lang));

        if(Yii::app()->request->isPostRequest )
        {
            $model->attributes = $_POST['Infopage'];
            if($model->save())
                $this->redirect('/site/index');

        }

        $this->render('create',array(
            'model'=>$model
        ));
    }

    public function actionDelete($id,$lang){
        $model = Infopage::model()->findByAttributes(array('id'=>$id,'language'=>$lang));
        $model->delete();
        $this->redirect('/admin/infopageIndex');
    }
}

protected/controllers/PostsController.php
<?php
class PostsController extends Controller{

    public $layout='//layouts/simple';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl',
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'views' actions
                'actions'=>array('view','index'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('create','update','delete'),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array(''),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function actionCreate($id = null,$lang = null)
    {
        /**
         * @var $model Posts
         */
        $model = Posts::model()->findByAttributes(array('id'=>$id,'language'=>$lang));
        if(!empty($model)){
            $this->redirect(array('update','id'=>$model->id,'lang'=>$model->language));
        }
        $model = new Posts();
        if(!empty($id) && !empty($lang)){
            $model->id = $id;
            $model->language = $lang;
        }
        else{
            $model->language = 'ru';
        }
        $model->save();
        $this->redirect(array('update','id'=>$model->id,'lang'=>$model->language));
    }

    public function actionUpdate($id,$lang)
    {
        /**
         * @var $model Posts
         */
        $this->layout = 'simple';
        $model = Posts::model()->findByAttributes(array('id'=>$id,'language'=>$lang));

        if(Yii::app()->request->isPostRequest )
        {
            $model->attributes = $_POST['Posts'];
            if($model->save())
                $this->redirect('/site/index');

        }

        $this->render('create',array(
            'model'=>$model
        ));
    }

    public function actionView($id){
        /**@var $model Posts*/

        $arrayLanguages = array('ru','uk','en');
        $lang = $_REQUEST['languages'];
        $this->layout = "simple";
        $model = Posts::model()->findByAttributes(array('id'=>$id,'language'=>$lang));

        foreach($arrayLanguages as $one){
            if($one != $lang){
                $model  = Posts::model()->findByAttributes(array('id'=>$id,'language'=>$one));
                if(!empty($model)) break;
            }
        }
//        if(empty($model)){
//            $language = (($_REQUEST['language'] == 'ru')?'uk':'ru');
//            $model  = Posts::model()->findByAttributes(array('id'=>$id,'language'=>$language));
//        }

        $this->pageDescription = $model->seoDescription;
        $this->pageKeywords = $model->seoKeywords;
        $this->pageTitle = $model->seoTitle;

        $this->render('view',array(
            'model'=>$model
        ));
    }

    public function actionIndex($categoryId = null){
        $params = array(':lang'=>$_REQUEST['language']);
        $sqlWhere = '';

        if(!empty($categoryId)){
            $sqlWhere = ' AND P.categoryId = :categoryId ';
            $params[':categoryId'] = $categoryId;
        }

        $languageIds = Yii::app()->db->createCommand("SELECT id FROM Posts P WHERE P.language = :lang $sqlWhere")->queryColumn($params);
        $languageIds = implode(',',$languageIds);
        $countLang = Yii::app()->db->createCommand(" SELECT count(*) FROM Posts P WHERE P.language = :lang $sqlWhere")->queryScalar($params);
        $newParam = array();
        $newParam[':lang'] = (($_REQUEST['language'] == 'ru')?'uk':'ru');

        $sqlP = '';$sqlPNew = '';$sqlWhereNew = ' ';
        if(!empty($languageIds)){
            $sqlP = " AND P.id not in (".$languageIds.") ";
            $sqlPNew = " AND P1.id not in (".$languageIds.") ";
        }
        if(!empty($categoryId)){
            $newParam[':categoryId'] = $categoryId;
            $sqlWhereNew = ' AND P1.categoryId = :categoryIdNew ';
            $params[':categoryIdNew'] = $categoryId;
        }

        $sqlNotLangCount = "SELECT count(*) FROM Posts P WHERE P.language = :lang $sqlP $sqlWhere ";
        $countNotLang = Yii::app()->db->
            createCommand("$sqlNotLangCount")->queryScalar($newParam);

        $category = Category::model()->findAll();

        $params[':notLang'] = (($_REQUEST['language'] == 'ru')?'uk':'ru');
        $sqlData = "SELECT * FROM(
                        SELECT * FROM Posts P WHERE P.`language` = :lang $sqlWhere
                            UNION
                        SELECT * FROM Posts P1 WHERE P1.`language` = :notLang $sqlPNew $sqlWhereNew
                    ) R ORDER BY R.id DESC";

        $dataProvider = new CSqlDataProvider("$sqlData",array(
            'keyField'=>'id',
            'totalItemCount'=>($countLang + $countNotLang),
            'pagination' => array(
                'pageSize' =>3,
            ),
            'params'=>$params
        ));

        $this->render('index',array(
            'dataProvider'=>$dataProvider,
            'category'=>$category
        ));
    }

    public function actionDelete($id,$lang){
        $model = Posts::model()->findByAttributes(array('id'=>$id,'language'=>$lang));
        $model->delete();
        $this->redirect('/admin/postsIndex');
    }
}

protected/views/admin/_category.php
<?/**
 * @var $data array()
 * @var $index
 */?>
<li style="height: auto;margin:0 0 20px 0;">
    <div class="extra-wrap">
        <h6 class="p2">
            <?=CHtml::link($data['title'].' - language : '.$data['language']
                ,array('/category/update','id'=>$data['id']))?>
            <span style="width:50px;display: inline-block"></span>
            <?=CHtml::link('delete-'.$data['id'],array('/category/delete','id'=>$data['id'],'lang'=>$data['language']))?>
            <span style="width: 50px;display: inline-block"></span>

            <?$arrayLang = array('uk','ru','en');?>
            <?foreach($arrayLang as $one):?>
                <?if($one != $data['language']):?>
                    <?=CHtml::link('create/update '.$data['id'].' lang '.$one,
                        array('/category/create','id'=>$data['id'],'lang'=>$one))?>
                <?endif;?>
            <?endforeach?>
        </h6>
        <?=Posts::smallContent($data['content'])?>
        <p style="font:normal 13px Arial;color:#9595c3;">ParentId - <?=$data['parentId']?></p>
        <?=CHtml::link('Read More',array('/posts/view','id'=>$data['id']),array('class'=>'link-2'))?>
    </div>
</li>
<hr />

protected/views/admin/_feedback.php
<?/**
 * @var $data array()
 * @var $index
 */?>
<li style="height: auto;margin:0 0 20px 0;">
    <div class="extra-wrap">
        <h6 class="p2"><?=$data['name']?> <?=CHtml::link('delete-feedback-'.$data['id'],
                array('/feedback/delete','id'=>$data['id']),array('style'=>'float:right;'))?></h6>
        <?=$data['content']?>
        <p style="font:normal 13px Arial;color:#9595c3;">Email - <?=$data['email']?></p>
        <p style="font:normal 13px Arial;color:#9595c3;">Phone - <?=$data['phone']?></p>
    </div>
    <hr />
</li>

protected/views/admin/_image.php
<?/**
 * @var $data array()
 * @var $index
 */?>
<li style="height: auto;margin:0 0 20px 0;">
    <div class="extra-wrap">
        <h6 class="p2">
            <span style="width: 50px;display: inline-block"></span>
            <img src="/images/pictures/<?=$data['id'].'.'.$data['extension']?>" style="float:left;">
            <input value="<?=YiiBase::getPathOfAlias('webroot').'/images/pictures/'.$data['id'].'.'.$data['extension']?>"
                style="width:380px;margin:0 0 0 7px;">
            <span style="width: 50px;display: inline-block"></span>
        </h6>
    </div>
</li>
<hr >

protected/views/admin/_info.php
<?/**
 * @var $data array()
 * @var $index
 */?>
<li style="height: auto;margin:0 0 20px 0;">
    <div class="extra-wrap">
        <h6 class="p2">
            <?=CHtml::link($data['title'].' - language : '.$data['language']
                ,array('/posts/update','id'=>$data['id']))?>
            <span style="width: 50px;display: inline-block"></span>
            <?=CHtml::link('delete-'.$data['id'],array('/infopage/delete','id'=>$data['id'],'lang'=>$data['language']))?>
            <span style="width: 50px;display: inline-block"></span>

            <?$arrayLang = array('uk','ru','en');?>
            <?foreach($arrayLang as $one):?>
                <?if($one != $data['language']):?>
                    <?=CHtml::link('create/update '.$data['id'].' lang '.$one,
                        array('/infopage/create','id'=>$data['id'],'lang'=>$one))?>
                <?endif;?>
            <?endforeach?>

            </h6>

        <?=Posts::smallContent($data['content'])?><br />
        <?=CHtml::link('Read More',array('/posts/view','id'=>$data['id']),array('class'=>'link-2'))?>
    </div>
</li>
<hr />

protected/views/admin/_post.php
<?/**
 * @var $data array()
 * @var $index
 */?>
<li style="height: auto;margin:0 0 20px 0;">
    <div class="extra-wrap">
        <h6 class="p2"><?=CHtml::link($data['title'].' - language : '.$data['language'],
                array('/posts/update','id'=>$data['id'],'lang'=>$data['language']))?>
            <span style="width: 50px;display: inline-block"></span>
            <?=CHtml::link('delete-'.$data['id'],array('/posts/delete','id'=>$data['id'],'lang'=>$data['language']))?>
            <span style="width: 50px;display: inline-block"></span>
            <?$arrayLang = array('uk','ru','en');?>
            <?foreach($arrayLang as $one):?>
                <?if($one != $data['language']):?>
                    <?=CHtml::link('create/update '.$data['id'].' lang-'.$one,
                        array('/posts/create','id'=>$data['id'],'lang'=>$one))?>
                <?endif;?>
            <?endforeach?>
        </h6>
        <?=Posts::smallContent($data['content'])?>
        <?=CHtml::link('Read More',array('/posts/view','id'=>$data['id']),array('class'=>'link-2'))?>
    </div>
</li>
<hr >

protected/views/admin/_slider.php
<?/**
 * @var $data array()
 * @var $index
 */?>
<li style="height: auto;margin:0 0 20px 0;">
    <div class="extra-wrap">
        <h6 class="p2"><?=CHtml::link($data['title'],
                array('/sliderImage/update','id'=>$data['id']))?>
<!--            <span style="width: 50px;display: inline-block"></span>-->
<!--            --><?//$arrayLang = array('uk','ru','en');?>
<!--            --><?//foreach($arrayLang as $one):?>
<!--                --><?//if($one != $data['language']):?>
<!--                    --><?//=CHtml::link('create/update '.$data['id'].' lang-'.$one,
//                        array('/sliderImage/createText','id'=>$data['id'],'lang'=>$one))?>
<!--                --><?//endif;?>
<!--            --><?//endforeach?>
            <span style="width: 50px;display: inline-block"></span>
            <br />
            <br />
            <p>Title : '<?=$data['title']?>'<br /> url : '<?=$data['url']?>'<br /> language : '<?=$data['language']?>'<br />
                parent : '<?=$data['parent']?>'<br /> place : '<?=$data['place']?>'</p>
        </h6>
    </div>
</li>
<hr >

protected/views/admin/categoryIndex.php
<?/**
 * @var $dataProvider CSqlDataProvider
 * @var $this PostsController
 * @var $category array()
 * @var $one Category
 */?>
<section id="content">
    <div class="content-bg">
        <div class="container_24">
            <div class="wrapper">
                <article class="grid_8">
                    <div class="indent bcolor-1 prev-indent-bot">
                        <?$this->renderPartial('//block/adminMenu');?>
                    </div>
                    <figure><a href="#"><img src="/images/bunner-1.jpg" alt="" /></a></figure>
                </article>
                <article class="grid_16">
                    <h3 class="margin-top">Спиок статей</h3>
                    <div class="slider-wrapper">
                        <ul id="slider" style="height: auto">
                            <?php if(!empty($dataProvider)): ?>
                                <?php
                                $this->widget('zii.widgets.CListView', array(
                                    'dataProvider'=>$dataProvider,
                                    'itemView'=>'_category',
                                    'htmlOptions'=>array(
                                        'class' => 'index-pagination'
                                    ),
                                    'ajaxUpdate'=>false,
                                    'template' => '{items}{pager}',
                                    'pager' => array(
                                        'firstPageLabel'=>'',
                                        'prevPageLabel'=>'<span class="a">Предыдущие</span>',
                                        'nextPageLabel'=>'<span class="a2">Далее</span>',
                                        'nextPageCssClass' => 'gogo',
                                        'previousPageCssClass' => 'empty',
                                        'lastPageLabel'=>'',
                                        'maxButtonCount'=>'4',
                                        'header'=>'',
                                        'htmlOptions' => array(
                                            'class'=>'pagination small'
                                        ),
                                    ),
                                ));
                                ?>
                            <?php endif ?>
                        </ul>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>

protected/views/admin/imageIndex.php
<?/**
 * @var $dataProvider CSqlDataProvider
 * @var $this AdminController
 */?>
<section id="content">
    <div class="content-bg">
        <div class="container_24">
            <div class="wrapper">
                <article class="grid_8">
                    <div class="indent bcolor-1 prev-indent-bot">
                        <?$this->renderPartial('//block/adminMenu');?>
                    </div>
                    <figure><a href="#"><img src="/images/bunner-1.jpg" alt="" /></a></figure>
                </article>
                <article class="grid_16">
                    <h3 class="margin-top">Спиок картинок</h3>
                    <div class="slider-wrapper">
                        <h3 class="margin-top"><?=CHtml::link('Создать картинку',array('/images/create'),
                                array('style'=>'font-size: 13px;float: right;line-height: 93px'))?></h3>
                        <ul id="slider" style="height: auto">
                            <?php if(!empty($dataProvider)): ?>
                                <?php
                                $this->widget('zii.widgets.CListView', array(
                                    'dataProvider'=>$dataProvider,
                                    'itemView'=>'_image',
                                    'htmlOptions'=>array(
                                        'class' => 'index-pagination'
                                    ),
                                    'ajaxUpdate'=>false,
                                    'template' => '{items}{pager}',
                                    'pager' => array(
                                        'firstPageLabel'=>'',
                                        'prevPageLabel'=>'<span class="a">Предыдущие</span>',
                                        'nextPageLabel'=>'<span class="a2">Далее</span>',
                                        'nextPageCssClass' => 'gogo',
                                        'previousPageCssClass' => 'empty',
                                        'lastPageLabel'=>'',
                                        'maxButtonCount'=>'4',
                                        'header'=>'',
                                        'htmlOptions' => array(
                                            'class'=>'pagination small'
                                        ),
                                    ),
                                ));
                                ?>
                            <?php endif ?>
                        </ul>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>

protected/views/admin/infopageIndex.php
<?/**
 * @var $dataProvider CSqlDataProvider
 * @var $this PostsController
 * @var $category array()
 * @var $one Category
 */?>
<section id="content">
    <div class="content-bg">
        <div class="container_24">
            <div class="wrapper">
                <article class="grid_8">
                    <div class="indent bcolor-1 prev-indent-bot">
                        <?$this->renderPartial('//block/adminMenu');?>
                    </div>
                    <figure><a href="#"><img src="/images/bunner-1.jpg" alt="" /></a></figure>
                </article>
                <article class="grid_16">
                    <h3 class="margin-top">Спиок статей <?=CHtml::link('Создать новий',array('/infopage/create'),
                            array('style'=>'font-size: 13px;float: right;line-height: 93px'))?></h3>
                    <div class="slider-wrapper">
                        <ul id="slider" style="height: auto">
                            <?php if(!empty($dataProvider)): ?>
                                <?php
                                $this->widget('zii.widgets.CListView', array(
                                    'dataProvider'=>$dataProvider,
                                    'itemView'=>'_info',
                                    'htmlOptions'=>array(
                                        'class' => 'index-pagination'
                                    ),
                                    'ajaxUpdate'=>false,
                                    'template' => '{items}{pager}',
                                    'pager' => array(
                                        'firstPageLabel'=>'',
                                        'prevPageLabel'=>'<span class="a">Предыдущие</span>',
                                        'nextPageLabel'=>'<span class="a2">Далее</span>',
                                        'nextPageCssClass' => 'gogo',
                                        'previousPageCssClass' => 'empty',
                                        'lastPageLabel'=>'',
                                        'maxButtonCount'=>'4',
                                        'header'=>'',
                                        'htmlOptions' => array(
                                            'class'=>'pagination small'
                                        ),
                                    ),
                                ));
                                ?>
                            <?php endif ?>
                        </ul>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>

protected/views/admin/pictureForSliders.php
<?php
/** @var $this ImageController
 * @var $form CActiveForm
 * @var $model Image
 */
?>
<?php $form = $this->beginWidget('CActiveForm', array(
    'id'=>'images-form',
    'enableAjaxValidation'=>false,
    'htmlOptions' => array('enctype' => 'multipart/form-data'), // ADD THIS
)); ?>
<?=$form->textField($model,'id',array('style'=>'display:none;')); ?>

<div class="field">
    <?php $this->widget('CMultiFileUpload', array(
        'model'      => $model,
        'attribute'  => 'extension',
        'accept'     => 'jpg|gif|png|jpeg',
        'max' => 1,
        'duplicate'  => Yii::t('main','Файл загружен'),
        'options'    => array(),
    ));?>
</div>
<div class="field1">
    <?=CHtml::submitButton('Save'); ?>
</div>
<?php $this->endWidget(); ?>

protected/views/admin/postsIndex.php
<?/**
 * @var $dataProvider CSqlDataProvider
 * @var $this PostsController
 * @var $category array()
 * @var $one Category
 */?>
<section id="content">
    <div class="content-bg">
        <div class="container_24">
            <div class="wrapper">
                <article class="grid_8">
                    <div class="indent bcolor-1 prev-indent-bot">
                        <?$this->renderPartial('//block/adminMenu');?>
                    </div>
                    <figure><a href="#"><img src="/images/bunner-1.jpg" alt="" /></a></figure>
                </article>
                <article class="grid_16">
                    <h3 class="margin-top">Спиок статей <?=CHtml::link('Создать новий',array('/posts/create'),
                            array('style'=>'font-size: 13px;float: right;line-height: 93px'))?></h3>
                    <div class="slider-wrapper">
                        <ul id="slider" style="height: auto">
                            <?php if(!empty($dataProvider)): ?>
                                <?php
                                $this->widget('zii.widgets.CListView', array(
                                    'dataProvider'=>$dataProvider,
                                    'itemView'=>'_post',
                                    'htmlOptions'=>array(
                                        'class' => 'index-pagination'
                                    ),
                                    'ajaxUpdate'=>false,
                                    'template' => '{items}{pager}',
                                    'pager' => array(
                                        'firstPageLabel'=>'',
                                        'prevPageLabel'=>'<span class="a">Предыдущие</span>',
                                        'nextPageLabel'=>'<span class="a2">Далее</span>',
                                        'nextPageCssClass' => 'gogo',
                                        'previousPageCssClass' => 'empty',
                                        'lastPageLabel'=>'',
                                        'maxButtonCount'=>'4',
                                        'header'=>'',
                                        'htmlOptions' => array(
                                            'class'=>'pagination small'
                                        ),
                                    ),
                                ));
                                ?>
                            <?php endif ?>
                        </ul>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>