protected/controllers/FeedbackController.php
<?php
class FeedbackController extends  Controller{

    public function actionSend(){
        if(Yii::app()->request->isAjaxRequest){
            if(isset($_REQUEST['email']) OR isset($_REQUEST['phone'])){
                $feedback = new Feedback();
                if(isset($_REQUEST['email'])) $feedback->email = $_REQUEST['email'];
                if(isset($_REQUEST['name'])) $feedback->name = $_REQUEST['name'];
                if(isset($_REQUEST['phone'])) $feedback->phone = $_REQUEST['phone'];
                if(isset($_REQUEST['text'])) $feedback->content = $_REQUEST['text'];
                $feedback->save();

                $message = new YiiMailMessage();
                $message->view = 'email_feedback';
                $message->subject = 'Обратная связь';
                $message->setBody(array('model' => $feedback), 'text/html');
                $message->setTo(array('a-gizhan@mail.ru'));
                Yii::app()->mail->send($message);

                echo json_encode(array('answer'=>true));
            }
            else
                echo json_encode(array('answer'=>false));

        }
    }

    public function actionDelete($id){
        /**@var $model Feedback*/
        $model = Feedback::model()->findByPk($id);
        $model->active = 0;
        $model->save();
        $this->redirect('/admin/feedbackIndex');
    }
}

protected/views/block/adminMenu.php
<h4 class="p0" style="font-size: 14px">Список административних сраничек</h4>
<ul class="list-2">
    <li><?=CHtml::link('статьи',array('admin/postsIndex'))?></li>
    <li><?=CHtml::link('инфо странички',array('admin/infopageIndex'))?></li>
    <li><?=CHtml::link('категории',array('admin/categoryIndex'))?></li>
    <li><?=CHtml::link('оратная связь',array('admin/feedbackIndex'))?></li>
    <li><?=CHtml::link('картинки',array('admin/imageIndex'))?></li>
    <li><?=CHtml::link('слайдер',array('admin/sliderImage'))?></li>
    <li><?=CHtml::link('картинки для маленьких слайдерів',array('admin/pictureForSliders'))?></li>
</ul>

protected/views/block/feedback.php
<div class="indent bcolor-1">
    <h4 class="p2 title-feedback"  style="font-size: 27px"><?=t('block','Обратная связь')?></h4>
    <form id="contact-form">
        <div class="success"> Contact form submitted!<br>
            <strong>We will be in touch soon.</strong> </div>
        <fieldset>
            <label class="name">
                <input id="feedback-fio" type="text" value="" placeholder="<?=t('block','ФИО')?>">
                <span class="error">*This is not a valid name.</span> <span class="empty">*This field is required.</span>
            </label>
            <label class="email">
                <input id="feedback-mail" type="text" value="" placeholder="E-mail">
                <span class="error">*This is not a valid email address.</span> <span class="empty">*This field is required.</span>
            </label>
            <label class="phone">
                <input id="feedback-phone" type="text" value="" placeholder="<?=t('block','Телефон')?>">
                <span class="error">*This is not a valid phone number.</span> <span class="empty">*This field is required.</span>
            </label>
            <label class="message">
                <textarea id="feedback-text" placeholder="<?=t('block','Текст сообшения')?>"></textarea>
                <span class="error">*Is too short message.</span> <span class="empty">*This field is required.</span> </label>

            <div class="feedbackErrorMessage" style="font: normal 13px Arial;color:#ec8e83;"></div>
            <div class="buttons-wrapper">
                <a id="clear-feedback" class="link-2" data-type="reset"><?=t('block','Очистить')?></a>
                <a id="feedback-send" class="link-2" data-type="submit"><?=t('block','Послать')?></a>
            </div>
        </fieldset>
    </form>
    <script>
        $(document).ready(function(){
            var $fio = $('#feedback-fio');
            var $mail = $('#feedback-mail');
            var $phone = $('#feedback-phone');
            var $text = $('#feedback-text');
            function clearFeedback(){
                $fio.val('');
                $mail.val('');
                $phone.val('');
                $text.val('');
            }
            $('#clear-feedback').click(function(){
               clearFeedback();
            });
            $('#feedback-send').click(function(){
                var $error = $('.feedbackErrorMessage');
                $.ajax({
                    type: "POST",
                    data: {'name':$fio.val(),'email':$mail.val(),'phone':$phone.val(),'text':$text.val()},
                    url: '/feedback/send',
                    dataType: "json"
                }).done(function(data){
                    clearFeedback();
                    if(data.answer)
                        $error.html('<?=t('block','Ваше сообщение будет рассмотрено в ближайшем времени')?>');
                    else $error.html('<?=t('block','Ошибка')?>');
                });
            });
        });
    </script>
</div>

protected/views/block/footer.php
<footer>
    <div class="container_24">
        <div class="wrapper p6">
            <article class="grid_7 spacer-1 maxheight">
                <h4 class="color-1 p0"><?=t('main','Сторінки')?></h4>
                <ul class="list-1">
                    <li><?=CHtml::link(t('main','Новые ветры'),array('/infoPage/view/1' , 'language'=>Yii::app()->language) ) ?></li>
                    <li><?=CHtml::link(t('main','Рисковая работа'),array('/infoPage/view/1' , 'language'=>Yii::app()->language) ) ?></li>
                    <li><?=CHtml::link(t('main','Экология'),array('/infoPage/view/1' , 'language'=>Yii::app()->language) ) ?></li>
                    <li><?=CHtml::link(t('main','Клуб "Экстрим"'),array('/infoPage/view/1' , 'language'=>Yii::app()->language) ) ?></li>
                    <li><?=CHtml::link(t('main','Кто культурнее?'),array('/infoPage/view/1' , 'language'=>Yii::app()->language) ) ?></li>
                    <li><?=CHtml::link(t('main','В прошлой жизни'),array('/infoPage/view/1' , 'language'=>Yii::app()->language) ) ?></li>
                </ul>
            </article>
            <article class="grid_10 spacer-2 maxheight">
                <h4 class="color-1 p0"><?=t('block','О нас пишут')?>:</h4>
                <ul class="list-services wrapper">
                    <li><?= CHtml::link('<div class="write type-1"></div>','http://blogs.lb.ua/alla_tsvetkova',array('target'=>"_blank"))?></li>
                    <li><?= CHtml::link('<div class="write type-2"></div>','http://www.aif.ua/health/964822',array('target'=>"_blank"))?></li>
                    <li><?= CHtml::link('<div class="write type-3"></div>','http://old.natali.ua/materials/show.html?p=5&id=2787',array('target'=>"_blank"))?></li>
                    <li><?= CHtml::link('<div class="write type-4"></div>','http://vn.20minut.ua/Zdorovya/159501',array('target'=>"_blank"))?></li>
                </ul>
                <h4 class="color-1 p0" style="display: inline-block; top: -10px;position: relative;"><?=t('block','Поделиться')?>:</h4>\
                <div class="share42init" style="display: inline-block"></div>
                <script type="text/javascript" src="/js/share42/share42.js"></script>
            </article>
            <article class="grid_7 maxheight feedback-footer">
                <?$this->renderPartial('//block/feedback')?>
            </article>
        </div>
    </div>
    <div class="footer-row">
        <strong>© 2013 - <?=date("Y")?> Юрсана - клуб здорового образа жизни. Все права защищены. <?= CHtml::link('yursana.com','http://yursana.com/',array('class'=>'link-for-site'))?>.</strong>
    </div>
</footer>

protected/views/block/head.php
<head>
    <title><?=$this->pageTitle;?></title>
    <meta charset="utf-8">
    <link rel="stylesheet/less" type="text/css" href="/less/styles.less">
    <link rel="stylesheet" href="/css/reset.css" type="text/css" media="screen">
    <link rel="stylesheet" href="/css/style.css" type="text/css" media="screen">
    <link rel="stylesheet" href="/css/style.css" type="text/css" media="screen">
    <link rel="stylesheet" href="/css/grid.css" type="text/css" media="screen">
    <script src="/js/less.js" type="text/javascript"></script>
    <script src="/js/popup.js" type="text/javascript"></script>
    <?php Yii::app()->clientScript->registerPackage('jquery');?>

<!--    <div style=' clear: both; text-align:center; position: relative;'> -->
<!--        <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">-->
<!--            <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />-->
<!--        </a>-->
<!--    </div>-->
<!--    <![endif]-->
    <!--[if lt IE 9]>
    <script type="text/javascript" src="/js/html5.js"></script>
    <link rel="stylesheet" href="/css/ie.css" type="text/css" media="screen">
    <![endif]-->
    <?php Yii::app()->clientScript->registerPackage('jquery');?>
</head>

protected/views/block/header.php
<header>
    <div class="first-block">
        <?php $this->widget('ext.i18nTools.widgets.LanguageSelector',array(
            'type'=>'links',
        )); ?>
        <div class="clear"></div>
        <div id="contact">
            <span class="phone-number">576-17-96</span>
            <a  href="skype:gg.banderolka.?call"><div class="skype"></div></a>
        </div>
    </div>
    <div class="header-menu">
        <?$this->renderPartial('//block/menu')?>
    </div>
    <div class="clear"></div>
</header>

<div class="clear"></div>