protected/controllers/InfopageController.php
<?
class InfopageController extends Controller{

    public function filters()
    {
        return array(
            'accessControl',
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'views' actions
                'actions'=>array('contact','about','view'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('create','update','delete'),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array(''),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function actionContact(){
        $this->layout = 'simple';
        $this->render('contact',array(

        ));
    }

    public function actionAbout()
    {
        $this->layout = 'main';
        $this->render('about');
    }

    public function actionCreate($id = null,$lang = null)
    {
        /**
         * @var $model Infopage
         */
        $model = Infopage::model()->findByAttributes(array('id'=>$id,'language'=>$lang));
        if(!empty($model)){
            $this->redirect(array('update','id'=>$model->id,'lang'=>$model->language));
        }
        $model = new Infopage();
        if(!empty($id) && !empty($lang)){
            $model->id = $id;
            $model->language = $lang;
        }
        else{
            $model->language = 'ru';
        }
        $model->save();
        $this->redirect(array('update','id'=>$model->id,'lang'=>$model->language));
    }

    public function actionView($id){

        /**@var $model Infopage*/
        $arrayLanguages = array('ru','uk','en');
        $lang = $_REQUEST['languages'];

        $this->layout = "simple";
        $model = Infopage::model()->findByAttributes(array('id'=>$id,'language'=>$_REQUEST['language']));
//        if(empty($model)){
//            $language = (($_REQUEST['language'] == 'ru')?'uk':'ru');
//            $model  = Infopage::model()->findByAttributes(array('id'=>$id,'language'=>$language));
//        }
        foreach($arrayLanguages as $one){
            if($one != $lang){
            $model  = Infopage::model()->findByAttributes(array('id'=>$id,'language'=>$one));
                if(!empty($model)) break;
            }
        }

        $this->pageDescription = $model->seoDescription;
        $this->pageKeywords = $model->seoKeywords;
        $this->pageTitle = $model->seoTitle;

        $this->render('view',array(
            'model'=>$model
        ));
    }

    public function actionUpdate($id,$lang)
    {
        /**
         * @var $model Infopage
         */
        $this->layout = 'simple';
        $model = Infopage::model()->findByAttributes(array('id'=>$id,'language'=>$lang));

        if(Yii::app()->request->isPostRequest )
        {
            $model->attributes = $_POST['Infopage'];
            if($model->save())
                $this->redirect('/site/index');

        }

        $this->render('create',array(
            'model'=>$model
        ));
    }

    public function actionDelete($id,$lang){
        $model = Infopage::model()->findByAttributes(array('id'=>$id,'language'=>$lang));
        $model->delete();
        $this->redirect('/admin/infopageIndex');
    }
}

protected/controllers/PostsController.php
<?php
class PostsController extends Controller{

    public $layout='//layouts/simple';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl',
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'views' actions
                'actions'=>array('view','index'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('create','update','delete'),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array(''),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function actionCreate($id = null,$lang = null)
    {
        /**
         * @var $model Posts
         */
        $model = Posts::model()->findByAttributes(array('id'=>$id,'language'=>$lang));
        if(!empty($model)){
            $this->redirect(array('update','id'=>$model->id,'lang'=>$model->language));
        }
        $model = new Posts();
        if(!empty($id) && !empty($lang)){
            $model->id = $id;
            $model->language = $lang;
        }
        else{
            $model->language = 'ru';
        }
        $model->save();
        $this->redirect(array('update','id'=>$model->id,'lang'=>$model->language));
    }

    public function actionUpdate($id,$lang)
    {
        /**
         * @var $model Posts
         */
        $this->layout = 'simple';
        $model = Posts::model()->findByAttributes(array('id'=>$id,'language'=>$lang));

        if(Yii::app()->request->isPostRequest )
        {
            $model->attributes = $_POST['Posts'];
            if($model->save())
                $this->redirect('/site/index');

        }

        $this->render('create',array(
            'model'=>$model
        ));
    }

    public function actionView($id){
        /**@var $model Posts*/

        $arrayLanguages = array('ru','uk','en');
        $lang = $_REQUEST['languages'];
        $this->layout = "simple";
        $model = Posts::model()->findByAttributes(array('id'=>$id,'language'=>$lang));

        foreach($arrayLanguages as $one){
            if($one != $lang){
                $model  = Posts::model()->findByAttributes(array('id'=>$id,'language'=>$one));
                if(!empty($model)) break;
            }
        }
//        if(empty($model)){
//            $language = (($_REQUEST['language'] == 'ru')?'uk':'ru');
//            $model  = Posts::model()->findByAttributes(array('id'=>$id,'language'=>$language));
//        }

        $this->pageDescription = $model->seoDescription;
        $this->pageKeywords = $model->seoKeywords;
        $this->pageTitle = $model->seoTitle;

        $this->render('view',array(
            'model'=>$model
        ));
    }

    public function actionIndex($categoryId = null){
        $params = array(':lang'=>$_REQUEST['language']);
        $sqlWhere = '';

        if(!empty($categoryId)){
            $sqlWhere = ' AND P.categoryId = :categoryId ';
            $params[':categoryId'] = $categoryId;
        }

        $languageIds = Yii::app()->db->createCommand("SELECT id FROM Posts P WHERE P.language = :lang $sqlWhere")->queryColumn($params);
        $languageIds = implode(',',$languageIds);
        $countLang = Yii::app()->db->createCommand(" SELECT count(*) FROM Posts P WHERE P.language = :lang $sqlWhere")->queryScalar($params);
        $newParam = array();
        $newParam[':lang'] = (($_REQUEST['language'] == 'ru')?'uk':'ru');

        $sqlP = '';$sqlPNew = '';$sqlWhereNew = ' ';
        if(!empty($languageIds)){
            $sqlP = " AND P.id not in (".$languageIds.") ";
            $sqlPNew = " AND P1.id not in (".$languageIds.") ";
        }
        if(!empty($categoryId)){
            $newParam[':categoryId'] = $categoryId;
            $sqlWhereNew = ' AND P1.categoryId = :categoryIdNew ';
            $params[':categoryIdNew'] = $categoryId;
        }

        $sqlNotLangCount = "SELECT count(*) FROM Posts P WHERE P.language = :lang $sqlP $sqlWhere ";
        $countNotLang = Yii::app()->db->
            createCommand("$sqlNotLangCount")->queryScalar($newParam);

        $category = Category::model()->findAll();

        $params[':notLang'] = (($_REQUEST['language'] == 'ru')?'uk':'ru');
        $sqlData = "SELECT * FROM(
                        SELECT * FROM Posts P WHERE P.`language` = :lang $sqlWhere
                            UNION
                        SELECT * FROM Posts P1 WHERE P1.`language` = :notLang $sqlPNew $sqlWhereNew
                    ) R ORDER BY R.id DESC";

        $dataProvider = new CSqlDataProvider("$sqlData",array(
            'keyField'=>'id',
            'totalItemCount'=>($countLang + $countNotLang),
            'pagination' => array(
                'pageSize' =>3,
            ),
            'params'=>$params
        ));

        $this->render('index',array(
            'dataProvider'=>$dataProvider,
            'category'=>$category
        ));
    }

    public function actionDelete($id,$lang){
        $model = Posts::model()->findByAttributes(array('id'=>$id,'language'=>$lang));
        $model->delete();
        $this->redirect('/admin/postsIndex');
    }
}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{

		return array(

		);
	}

    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'views' actions
                'actions'=>array('index', 'categoryList', 'error', 'test', 'info'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array(''),
                'users'=>array('@'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function actionInfo()
    {

        $model = new UserInfo();
        if(isset($_POST['user']) && !empty($_POST['user']))
        {
            $model->user = $_POST['user'];
            $model->sex = $_POST['sex'];
            $model->birthday = $_POST['birthday'];
            $model->height = $_POST['height'];
            $model->weight = $_POST['weight'];
            if($model->save())
            {
                echo json_encode(array('massage'=>t('main','Мы получили ваши данные и в скором времени с вами свяжимся')));
                Yii::app()->end();
            }
        }
        $view = $this->renderPartial('info',array(
            'model' => $model,
        ),true);
        echo json_encode(array('view'=>$view));
    }

    public function actionIndex()
    {
        $criteria = new CDbCriteria();
        $criteria->condition = 'parentId = :parentId AND language = :language';
        $criteria->params = array(':parentId'=>0 , ':language'=>Yii::app()->language);
        $category = Category::model()->findAll($criteria);

        $sliderSql = " SELECT S.* , SS.submenu FROM Slider S
                        LEFT JOIN (SELECT GROUP_CONCAT(SL.title,'|',SL.url) submenu , SL.place FROM Slider SL
                        WHERE SL.parent = 1 AND SL.`language` = :lang GROUP BY SL.place)
                            SS ON SS.place = S.place
                            WHERE S.parent = 0 AND S.`language` = :lang ";
        $param = array();
        $param[':lang'] = Yii::app()->language;
        $slider = Yii::app()->db->createCommand(" $sliderSql ")->queryAll(true,$param);

        $this->render('index',array(
            'category'=>$category,
            'slider'=>$slider
        ));
    }

    public function actionCategoryList()
    {
        if($_POST['id'])
        {
            $idCategoryType = $_POST['id'];
            $criteria = new CDbCriteria();
            $criteria->condition = ('id = :id AND language = :language');
            $criteria->params = array(':id'=>$idCategoryType , ':language'=>Yii::app()->language);
            $model = Category::model()->find($criteria);
            $criteria = new CDbCriteria();
            $criteria->condition = 'parentId = :parentId AND language = :language';
            $criteria->params = array(':parentId'=>$model->id, ':language'=>Yii::app()->language);
            $category = Category::model()->findAll($criteria);



            $view = $this->renderPartial('categoryView',array(
                'category' => $category,
                'model'=>$model
            ),true);
          echo json_encode(array('view'=>$view));
        }
    }

    public function actionError()
    {
        $this->layout = "main";
        if($error=Yii::app()->errorHandler->error)
        {
            if(Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    public function actionTest(){


//        $this->layout = 'test';
//        $this->render('slider',array(
//            'slider'=>$slider,
//            'activeId'=>1
//        ));
    }

}

protected/views/site/categoryView.php
<div class="category-popup">
    <div class="about-category">
        <h1><?=$model->title?></h1>
        <p><?=$model->content?></p>
    </div>
    <div class="list-category">
        <?php if (!empty($category)):?>
        <?php foreach($category as $item):?>
            <?= CHtml::link('<p class="title">'.$item->title.'</p><p class="about">'.$item->content.'</p>',array('/posts/index', 'id'=>$item->id),array('class'=>'item-category'))?>
        <?php endforeach?>
        <?php else :?>
            <a class="item-category">
                Пока нет категорий :'(
            </a>
        <?php endif ?>
    </div>
</div>

protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

protected/views/site/index.php
<?$this->renderPartial('/site/slider',array('slider'=>$slider,'activeId'=>1));?>
<div class="convas-box">
    <div class="index-main" style="margin: 0 auto">
        <div class="index-left-box">
            <div class="slider-goroskop">
                <div class="small-slider">
                    <link href="/js/simpleSlider/fotorama.css" rel="stylesheet">
                    <script src="/js/simpleSlider/fotorama.js"></script>
                    <div class="fotorama" data-width="630" data-height="255" data-autoplay="true" data-nav="thumbs">
                        <a href="/images/middleSlide/slider1.png"><img src="/images/middleSlide/slider1.png" width="630" height="324"></a>
                        <a href="/images/middleSlide/slider2.png"><img src="/images/middleSlide/slider2.png" width="630" height="324"></a>
                    </div>
                </div>
                <?=CHtml::link('<p class="goroskop">'.t('main','Гороскоп похудения').'</p>',array('/infopage/view', 'id'=>3),array('class'=>'goroskop-box'))?>
            </div>
            <div class="types">
                <?php foreach($category as $item):?>
                    <?=CHtml::link('<figure class="category-'.$item->id.'"></figure>
                        <article class="grid_8 alpha in-category">
                            <div class="box-2">
                                <div class="padding">
                                    <strong class="title-1">'.$item->title.'</strong>
                                    <p class="border-bot1">'.Category::smallContent($item->content).'></p>
                                </div>
                            </div>
                        </article>',array('/posts/index', 'id'=>$item->id),array('class'=>'type','data-type'=>'1'))
                    ?>
                <?php endforeach?>
            </div>
        </div>
        <div class="index-right-box">
            <article class="grid_8 bcolor-1" style="margin: 5px 0;height: 384px;">
                <div class="indent">
                    <h4 class="border-bot3" style="font-size: 30px;">Алла Борисовна</h4>
                    <img src="../../../images/photo.png" style="height:134px;width: 134px;display: block;float:left;margin: 0 10px 0 0 ">
                    <p class="color-2">Тут будет какаято информацыя о Алле Борисовне , и немного текста о ней,
                        и немного текста о ней, и немного текста о ней, и немного текста о ней, и немного текста о ней
                        , и немного текста о ней, и немного текста о ней, и немного текста о ней, и немного текста о ней
                        , и немного текста о ней, и немного текста о ней, и немного текста о ней, и немного текста о ней...</p>
                    <div class="alignright">
                        <?=CHtml::link(t('main','Дальше'),array('/infopage/view','id'=>2),array('class'=>'link-2'))?>
                    </div>
                </div>
            </article>
            <article class="grid_8 bcolor-1" style="margin: 5px 0;height: 187px; width: 320px;">
                <div class="indent" >
                    <h4 class="border-bot3" style="font-size: 30px;line-height: 45px;">Школа домашнего диетолога</h4>
                    <div class="alignright">
                        <?=CHtml::link(t('main','Дальше'),array('/posts/index','language'=>'ru'),array('class'=>'link-2'))?>
                    </div>
                </div>
            </article>
            <article class="grid_8 bcolor-1" style="margin: 5px 0;height: 187px;width: 320px;">
                <div class="indent" >
                    <h4 class="border-bot3" style="font-size: 30px;">Дневник питания</h4>
                    <div class="alignright">
                        <?=CHtml::link(t('main','Дальше'),array('/posts/index','language'=>'ru'),array('class'=>'link-2'))?>
                    </div>
                </div>
            </article>
            <?php $this->widget('application.widgets.ResultsWidget', array()) ?>
        </div>
    </div>
</div>

protected/views/site/info.php
<div class="userInfo">
    <h4 class="border-bot3" style="font-size: 32px;margin: 0;"><?=t('main','Ваши персональные данные')?></h4>
    <div class="row">
        <label for="UserInfo_user">User</label>
        <input name="UserInfo[user]" id="UserInfo_user" type="text" maxlength="124">
    </div>
    <div class="row">
        <label for="UserInfo_sex">Sex</label>
        <select name="UserInfo[sex]" id="UserInfo_sex">
            <option value="male" selected="selected">Male</option>
            <option value="female">Female</option>
        </select>
    </div>
    <div class="row">
        <label for="UserInfo_birthday">Birthday</label>
        <input name="UserInfo[birthday]" id="UserInfo_birthday" type="text">
    </div>
    <div class="row">
        <label for="UserInfo_height">Height</label>
        <input name="UserInfo[height]" id="UserInfo_height" type="text">
    </div>
    <div class="row">
        <label for="UserInfo_weight">Weight</label>
        <input name="UserInfo[weight]" id="UserInfo_weight" type="text">
    </div>
    <div class="row">
        <button id="send-form">Send</button>
    </div>
</div>
<script>
    $(document).on('click','#send-form',function()
    {
        var $user = $('#UserInfo_user').val();
        var $sex = $('#UserInfo_sex').val();
        var $birthday = $('#UserInfo_birthday').val();
        var $height = $('#UserInfo_height').val();
        var $weight = $('#UserInfo_weight').val();
        $.ajax({
            url: '/site/info',
            data: {user:$user,sex:$sex,birthday:$birthday,height:$height,weight:$weight},
            type: "POST",
            dataType: 'json'
        }).done(function (data) {
            $('.userInfo').html(data.massage)
        }).error(function (error) {
            alert(error.messages)
        });
    });


</script>

protected/views/site/slider.php
<?
/**
 * @var $slider array()
 * @var $activeId
 */
$arrayPosition = array(0,239,428,617,806);
?>
<link rel="stylesheet" href="/css/slider.css" type="text/css" media="screen"/>
<style>
    a.back{
        position:absolute;
        width:150px;
        height:27px;
        outline:none;
        top:2px;
        right:0;
    }
    *{
        margin:0;
        padding:0;
    }
    <?foreach($slider as $key=>$one):?>
        .bg<?=($key+1)?>{
            background-image: url('/images/slider/<?=($key+1)?>.<?=$one['ext']?>');
        }
    <?endforeach;?>
</style>
<div id="content" style="margin: 0 auto;background-color: #fff;padding: 3px 0 0;">
    <div id="menuWrapper" class="menuWrapper bg1" style="margin: 0 auto">
        <ul class="menu" id="menu">
            <?foreach($slider as $key=>$one):?>
                <li class="bg<?=$activeId?> <?=(($key == 4)?'last':'')?> <?=(($key == 0)?'new-menu':'')?>"
                        style="background-position: -<?=$arrayPosition[$key]?>px 0">
                    <a id="bg<?=$key+1?>" href="<?=$one['url']?>"><?=$one['title']?></a>
                    <?if(!empty($one['submenu'])):?>
                        <?$subMenu=explode(',',$one['submenu'])?>
                    <ul class="sub<?=$key+1?>" style="background-position:-239px 0;">
                        <?foreach($subMenu as $link):?>
                            <?$oneElement=explode('|',$link);?>
                            <li><a href="<?=$oneElement[1]?>"><?=$oneElement[0]?></a></li>
                        <?endforeach;?>
                    </ul>
                    <?endif;?>
                </li>
            <?endforeach;?>
        </ul>
    </div>
</div>
<script type="text/javascript" src="/js/jquery.bgpos.js"></script>

<script type="text/javascript">
    $(function() {
        var current = 0;
        var loaded  = 0;
        for(var i = 1; i <6; ++i)
            $('<img />').load(function(){
                ++loaded;
                if(loaded == 5){
                    $('#bg1,#bg2,#bg3,#bg4,#bg5').mouseover(function(e){
                        var $this = $(this);
                        if($this.parent().index() == current)
                            return;
                        var item = e.target.id;
                        if(item == 'bg1' || current == 4)
                            $('#menu .sub'+parseInt(current+1)).stop().animate({backgroundPosition:"(-239px 0)"},300,function(){
                                $(this).find('li').hide();
                            });
                        else
                            $('#menu .sub'+parseInt(current+1)).stop().animate({backgroundPosition:"(189px 0)"},300,function(){
                                $(this).find('li').hide();
                            });
                        if(item == 'bg1' || current == 4){

                            $('#menu > li').animate({backgroundPosition:"(-999px 0)"},0).removeClass('bg1 bg2 bg3 bg4 bg5').addClass(item);
                            move(1,item);
                        }
                        else{
                            $('#menu > li').animate({backgroundPosition:"(999px 0)"},0).removeClass('bg1 bg2 bg3 bg4 bg5').addClass(item);
                            move(0,item);
                        }
                        if(current == 4 && item == 'bg1'){
                            $('#menu .sub'+parseInt(current)).stop().animate({backgroundPosition:"(-239px 0)"},300);
                        }
                        if(current == 0 && item == 'bg5'){
                            $('#menu .sub'+parseInt(current+2)).stop().animate({backgroundPosition:"(189px 0)"},300);
                        }
                        current = $this.parent().index();
                        $('#menu .sub'+parseInt(current+1)).stop().animate({backgroundPosition:"(0 0)"},300,function(){
                            $(this).find('li').fadeIn();
                        });
                    });
                }
            }).attr('src', '/../images/slider/'+i+'.jpg');
        function move(dir,item){
            if(dir){
                $('#bg1').parent().stop().animate({backgroundPosition:"(0 0)"},200);
                $('#bg2').parent().stop().animate({backgroundPosition:"(-239px 0)"},300);
                $('#bg3').parent().stop().animate({backgroundPosition:"(-428px 0)"},400);
                $('#bg4').parent().stop().animate({backgroundPosition:"(-617px 0)"},500);
                $('#bg5').parent().stop().animate({backgroundPosition:"(-806px 0)"},600,function(){
                    $('#menuWrapper').removeClass('bg1 bg2 bg3 bg4 bg5').addClass(item);
                });
            }
            else{
                $('#bg1').parent().stop().animate({backgroundPosition:"(0 0)"},400,function(){
                    $('#menuWrapper').removeClass('bg1 bg2 bg3 bg4 bg5').addClass(item);
                });
                $('#bg2').parent().stop().animate({backgroundPosition:"(-239px 0)"},300);
                $('#bg3').parent().stop().animate({backgroundPosition:"(-428px 0)"},300);
                $('#bg4').parent().stop().animate({backgroundPosition:"(-617px 0)"},300);
                $('#bg5').parent().stop().animate({backgroundPosition:"(-806px 0)"},200);
            }
        }
    });
</script>